//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.EmployeeFoods = new HashSet<EmployeeFood>();
        }
    
        public int F_id { get; set; }
        public string F_name { get; set; }
        public Nullable<int> F_quantity { get; set; }
        public Nullable<int> R_id { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<EmployeeFood> EmployeeFoods { get; set; }
        public virtual Restaurnt Restaurnt { get; set; }
        public int? AssignedEmployeeId { get; set; }
    }
}
