//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurnt
    {
        public Restaurnt()
        {
            this.Foods = new HashSet<Food>();
        }
    
        public int R_id { get; set; }
        public string R_name { get; set; }
        public string R_ownername { get; set; }
        public string R_address { get; set; }
    
        public virtual ICollection<Food> Foods { get; set; }
    }
}
